### PR TITLE
refactor: dry-fy functions

### PR DESCRIPTION
**Pull request by andreivladbrg**
I decided to dry fy `withdraw` and `renounce`. I couldn't find/remember why we didn't make this change earlier but I consider now that the code has been improved.

If you have a valid argument against this change I am happy to give up on this PR.

Note: I am aware that we are checking twice the caller in `withdrawMaxAndTransfer`. Don't think is worth to optimize since this function is very rarely used.

### CODE REVIEW

**Comment by PaulRBerg** [comment]
We've closed PR #682. Can you rebase this PR from `2.1` and reimplement it?

**Review by PaulRBerg — CHANGES_REQUESTED** [review]
We've closed PR https://github.com/sablier-labs/v2-core/pull/682. Can you rebase this PR from 2.1 and reimplement it?

**Comment by andreivladbrg** [comment]
> We've closed PR https://github.com/sablier-labs/v2-core/pull/682. Can you rebase this PR from 2.1 and reimplement it?

Pushed now a commit. Lmk if you like this change

**Review by PaulRBerg — APPROVED** [review]
Great idea. PR looks good!

I also can't remember why we haven't written the functions like this in the first place. Perhaps we just didn't notice the potential optimization.

Happy to merge the PR as is, but as a precaution I suggest running the deep CI with a high number of fuzz runs after merging.

**Pull request merged**
