### PR TITLE
perf: remove unchecked in for loop

### PR DESCRIPTION
**Pull request by smol-ninja**
Closes https://github.com/sablier-labs/v2-core/issues/757.

### CODE REVIEW

**Comment by PaulRBerg** [comment]
Why did you create this PR, @smol-ninja?

Haven't we merged https://github.com/sablier-labs/v2-core/pull/783?

**Comment by smol-ninja** [comment]
Me and @andreivladbrg discussed on the slack to merge PRs in the same order as they are created to avoid conflicts (and address conflicts in the PRs that are created after). So with that logic, https://github.com/sablier-labs/v2-core/pull/779 shall be merged first. 

That's why I had to reset the staging branch and create this new PR (or could have just rebased later) since I could not undo the merged one.

**Comment by PaulRBerg** [comment]
Ok great thanks for confirming @smol-ninja.

**Comment by smol-ninja** [comment]
Commits pushed directly to staging.

**Pull request closed without merging**
