### PR TITLE
build: bump solc to v0.8.26

### PR DESCRIPTION
**Pull request by smol-ninja**
Closes https://github.com/sablier-labs/v2-core/issues/943

### CODE REVIEW

**Comment by PaulRBerg** [comment]
Doesn't this invalidate the recent audits?

**Review by PaulRBerg — APPROVED** [review]
lgtm but let's double check that the audit reports are not invalidated

**Comment by smol-ninja** [comment]
> lgtm but let's double check that the audit reports are not invalidated

None of the finding depends on solc version. So, this should not invalidate the audit findings. cc @andreivladbrg for comments, if any.

**Comment by PaulRBerg** [comment]
OK, then, let's merge it

**Review by andreivladbrg — APPROVED** [review]
no comments on my side

lgtm👍

**Pull request merged**
