### PR TITLE
Updating .tree file in adminable_unit_test

### PR DESCRIPTION
**Pull request by SensationalShubham**
#621 

1. Updating the `.tree` file of `transferAdmin.t.sol` from folder `Adminable` under unit tests to make it more Understandable & Readable by using Cucumber's [Gherkin](https://cucumber.io/docs/gherkin/) syntax

2. Gave more clarity about the 2 Admins in the 8th line from the previous file.

### CODE REVIEW

**Review by PaulRBerg — CHANGES_REQUESTED** [review]
Thanks for the PR, @SensationalShubham. Two change requests:

1. Remove the "Scenario" line. BTT is inspired by Gherkin, but it is not striving to be Gherkin.
2.  Update the modifiers in `transferAdmin.t.sol` to match the new tree

I will also make a few wording suggestions later today.

**Comment by PaulRBerg** [comment]
Also, for future PRs: could you make your branch name more specific, please? Something like `test/refactor-tree-files`.

**Comment by SensationalShubham** [comment]
I got it, I'll name them more precisely and start making changes as you suggested.

**Review by PaulRBerg — APPROVED** [review]

**Comment by PaulRBerg** [comment]
Closing in favor of #641, which implemented the same changes.

**Pull request closed without merging**
