### PR TITLE
Release v1.2.0

### PR DESCRIPTION
**Pull request by andreivladbrg**
Refer to `CHANGELOG.md` to see the changes.

### CODE REVIEW

**Review by PaulRBerg — APPROVED** [review]
I trust that this is good

**Review by smol-ninja — DISMISSED** [review]
LGTM too.

Weird that CI shows duplicate workflows.

**Comment by PaulRBerg** [comment]
No squash and merging - just merge.

**Comment by smol-ninja** [comment]
Rebase and Merge, right?

**Review by smol-ninja — APPROVED** [review]
LGTM

**Pull request merged**
