### PR TITLE
ci: add slither job

### PR DESCRIPTION
**Pull request by scorpion9979**
Addresses https://github.com/sablierhq/v2-core/issues/418.

### CODE REVIEW

**Comment by PaulRBerg** [comment]
FYI @scorpion9979, we've just made the repo public now - if you ever find a moment to rebase from `main` and re-configure Slither, we'd love to give this PR another shot!

However, it's worth noting that Slither still doesn't work with user-defined operators:

https://github.com/crytic/slither/issues/1989

So I'm unsure if we can make Slither work with V2 Core, but it's worth trying!

**Comment by scorpion9979** [comment]
Thanks, @PaulRBerg. I'll look into this and get back to you ASAP.

**Comment by scorpion9979** [comment]
@PaulRBerg  During my investigation of the problem, I was able to find a tiny bug in the Slither config that was causing the [Slither CI job to fail](https://github.com/sablier-labs/v2-core/actions/runs/5424602059/jobs/9864270240#step:4:1303) at the solc remapping and compilation step. After [addressing the bug](https://github.com/sablier-labs/v2-core/pull/431/commits/97c7bf954cc41c1ffd516ec3a3a33e0b7df9d6de), I was able to confirm that [the job is now failing](https://github.com/sablier-labs/v2-core/actions/runs/5424735193/jobs/9864588470?pr=431#step:4:206) due to having no support for the user-defined operators used in [prb-math](https://github.com/PaulRBerg/prb-math). Screenshots below:

image

c57090fa-3d76-4964-aeb0-098105cd6485

**Comment by PaulRBerg** [comment]
Thank you for your continued involvement in this PR, @scorpion9979! And sorry to hear that we can't merge this due to Slither not working with user-defined operators 😞

I will keep this PR open but I will mark it as backlog.

> Local run
> Output:

Thanks for sharing that.

Random pro tip: have you tried [Warp](https://twitter.com/PaulRBerg/status/1670725786679099392)? Their permalinks feature is pretty cool. The perfect solution for sharing terminal outputs as you did here.

**Comment by scorpion9979** [comment]
Thanks, @PaulRBerg. Hopefully user-defined operators will be supported in time.

Re Warp: I've looked into using it, but unfortunately it's not available on Linux which is what I personally use.

**Comment by scorpion9979** [comment]
@PaulRBerg Looks like Slither v0.10.0 fixes the crash on prb-math now, as mentioned in https://github.com/crytic/slither/issues/1989#issuecomment-1770332612. I've gone ahead and tested the repo locally, and I can confirm that it works as shown below. I've also gone ahead and merged the `main` branch into `ci/slither` in PR https://github.com/sablier-labs/v2-core/pull/713.

### Local Run
### Command:
`slither ./src --config-file slither.config.json`

### Version:
Slither 0.10.0

### Output:

image

**Comment by PaulRBerg** [comment]
Very cool, thanks for the update @scorpion9979. Could you please fix the git conflicts?

And @andreivladbrg, could you please assist Ahmed by reviewing this PR?

**Comment by scorpion9979** [comment]
@andreivladbrg PR https://github.com/sablier-labs/v2-core/pull/713 fixes the merge conflicts.

**Comment by andreivladbrg** [comment]
> @andreivladbrg PR https://github.com/sablier-labs/v2-core/pull/713 fixes the merge conflicts.

it seems it doesn't, there have been too many commits since this PR was created.

I think it would be better to start a new PR starting from main, and include this [change](https://github.com/sablier-labs/v2-core/blob/d00fd89e2e62b1ba52e7328628713f4f885bfedb/.github/workflows/ci.yml#L289-L319).

Can you work on this @scorpion9979 ?

**Comment by scorpion9979** [comment]
@andreivladbrg Done here: https://github.com/sablier-labs/v2-core/pull/714

**Comment by andreivladbrg** [comment]
Closing in favor of https://github.com/sablier-labs/v2-core/pull/714

**Pull request closed without merging**
