### PR TITLE
perf: return 0 in linear when startTime == blockTimestamp

### PR DESCRIPTION
**Pull request by andreivladbrg**
Closes https://github.com/sablier-labs/v2-core/issues/958

### CODE REVIEW

**Review by smol-ninja — APPROVED** [review]
LGTM

**Comment by PaulRBerg** [comment]
love the new LGTM meme games!

**Comment by PaulRBerg** [comment]
Didn't we have to update some of the concrete tests?

**Comment by smol-ninja** [comment]
Not in the current tree structure. This is the relevant test: https://github.com/sablier-labs/v2-core/blob/staging/test/integration/concrete/lockup-linear/streamed-amount-of/streamedAmountOf.tree and me and @andreivladbrg [debated at length here](https://github.com/sablier-labs/v2-core/pull/941#discussion_r1631382126) about it and decided to make some changes when we refactor tests with Bulloak.

**Pull request merged**
