### PR TITLE
feat: Implement `renounceMultiple`

### LINKED ISSUE #1052: Implement "renounceMultiple"
As discussed [here](https://github.com/sablier-labs/v2-core/discussions/1030#discussioncomment-10812780), we should implement a `renounceMultiple` function in `SablierV2Lockup` in order to allow senders to batch-renounce streams.

### PR DESCRIPTION
**Pull request by cxp-13**
Closes #1052

## Added 

- Add `renounceMultiple` to the contract section

## Changed

- Change the visibility of the renouncing function from external to public

## Tests:

- Test `renounceMultiple` under specific circumstances

### CODE REVIEW

**Comment by cxp-13** [comment]
> Great PR @cxp-13. There are some merge conflicts. Can you please resolve them and update the PR? Thank you.

I merged the staging branch on my own branch, and only a few files were in conflict. I fixed them, but why are there so many file modifications when I submit them.

**Comment by smol-ninja** [comment]
>  merged the staging branch on my own branch, and only a few files were in conflict. I fixed them, but why are there so many file modifications when I submit them.

I'd recommend to reset your local branch with the `staging` branch and then cherry-pick your commits.

```bash
$ git reset --hard origin/staging
$ git cherry-pick your_commit
```

**Comment by cxp-13** [comment]
```
cxp@CXPfromR9000P:~/solana_learn/v2-core$ forge build
[⠢] Compiling...
[⠒] Compiling 281 files with Solc 0.8.26
Error: 
solc exited with signal: 9 (SIGKILL)
<empty output>
```
When I first cloned and implemented this feature, the total compiled files were less than 200. At that time, it could be successfully compiled.
Then, I don't know which instruction it is. It will increase to over 280 files and my memory cannot handle compilation. Even if I switch to the `main` branch and execute `git checkout .` I executed `forget clean` again. It is also impossible to revert back to the state when it was first cloned.

**Comment by cxp-13** [comment]
> > merged the staging branch on my own branch, and only a few files were in conflict. I fixed them, but why are there so many file modifications when I submit them.
> 
> I'd recommend to reset your local branch with the `staging` branch and then cherry-pick your commits.
> 
> ```shell
> $ git branch temp
> $ git reset --hard origin/staging
> $ git cherry-pick your_commit
> ```
I understand what you mean, but I have already tried merging and submitting. Can we do this again?

**Comment by cxp-13** [comment]
```
cxp@CXPfromR9000P:~/solana_learn/v2-core$ bun run build:optimized
$ FOUNDRY_PROFILE=optimized forge build
[⠒] Compiling...
[⠢] Compiling 110 files with Solc 0.8.26
[⠆] Solc 0.8.26 finished in 100.15s
Compiler run successful!
```
Great, this method can compile successfully.

**Comment by smol-ninja** [comment]
@cxp-13 before we review it, I'd appreciate if you can fix the failing CI. In case you ain't aware of the Bulloak, you can find details about it in the [contributing guidelines](https://github.com/sablier-labs/v2-core/blob/main/CONTRIBUTING.md#pull-requests).

**Comment by cxp-13** [comment]
> @cxp-13 before we review it, I'd appreciate if you can fix the failing CI. In case you ain't aware of the Bulloak, you can find details about it in the [contributing guidelines](https://github.com/sablier-labs/v2-core/blob/main/CONTRIBUTING.md#pull-requests).

```
cxp@CXPfromR9000P:~/solana_learn/v2-core$ bulloak check test/core/integration/concrete/lockup/renounce-multiple/renounceMultiple.tree 
warn: an error occurred while parsing the solidity file
   --> test/core/integration/concrete/lockup/renounce-multiple/renounceMultiple.tree

warn: 1 check failed
```
I look the guide(https://github.com/alexfertel/bulloak?tab=readme-ov-file#installation). but it didn't show where the warn at the file.

**Comment by cxp-13** [comment]
> @cxp-13 before we review it, I'd appreciate if you can fix the failing CI. In case you ain't aware of the Bulloak, you can find details about it in the [contributing guidelines](https://github.com/sablier-labs/v2-core/blob/main/CONTRIBUTING.md#pull-requests).

```
Run forge test --match-path "test/{core,periphery}/fork/**/*.sol"
No files changed, compilation skipped

Ran 1 test for test/core/fork/assets/SHIB.t.sol:SHIB_LockupDynamic_Fork_Test
[FAIL: setup failed: vm.createSelectFork: Could not instantiate forked environment with fork url: ] setUp() (gas: 0)
Suite result: FAILED. 0 passed; 1 failed; 0 skipped; finished in 2.[14](https://github.com/sablier-labs/v2-core/actions/runs/11292070279/job/31410776543?pr=1061#step:6:15)ms (0.00ns CPU time)

Ran 1 test for test/core/fork/assets/USDC.t.sol:USDC_LockupLinear_Fork_Test
[FAIL: setup failed: vm.createSelectFork: Could not instantiate forked environment with fork url: ] setUp() (gas: 0)
Suite result: FAILED. 0 passed; 1 failed; 0 skipped; finished in 2.[15](https://github.com/sablier-labs/v2-core/actions/runs/11292070279/job/31410776543?pr=1061#step:6:16)ms (0.00ns CPU time)
```
My change don't involved the `fork` folder. but it's all test case are fail.

**Comment by smol-ninja** [comment]
Don't worry about failing fork tests on CI. They don't work on PRs created by external contributors. We are still looking for a solution for that.﻿

**Pull request closed without merging**
