### PR TITLE
Move precompiles to precompiles directory

### LINKED ISSUE #789: Move the precompiles to `script`
As discussed [here](https://github.com/sablier-labs/v2-periphery/issues/238), it would be helpful to ship the precompiles so that we can write a protocol deployment script that spans V2 Core and V2 Periphery.

Task:

- [ ] Move the precompiles in the `script` directory
- [ ] Include the `script/Precompiles.s.sol` file in the npm package (via `files`)

Food for thought: or maybe we shouldn't include the precompiles in `script`? How about another directory, e.g., `precompiles`?

I will let you @andreivladbrg and @smol-ninja self-organize.

### PR DESCRIPTION
**Pull request by smol-ninja**
Resolves #789.

### CODE REVIEW

**Review by PaulRBerg — APPROVED** [review]
looks good so far

**Review by andreivladbrg — CHANGES_REQUESTED** [review]
Let's ignore the precompiles dir in the `.codecove.yaml` file because coverage has significantly decreased even though the file is tested.

https://github.com/sablier-labs/v2-core/blob/refactor/precompiles-directory/codecov.yml

Let's first merge #839 and then rebase from `refactor/remove-protocol-fee` to remove comptroller precompiles.

**Comment by smol-ninja** [comment]
Andrei, I have included your suggestions. lmk if it looks good now.

**Review by andreivladbrg — APPROVED** [review]
Looks good now, thank you

**Pull request merged**
