### PR TITLE
chore: bump solhint, integrate Husky and lint-staged

### PR DESCRIPTION
**Pull request by smol-ninja**
### Changelog
- Closes https://github.com/sablier-labs/v2-core/issues/978
- Bump solhint to `5.0.3`
    - Add a new rule to solhint: `imports-order`
    - Fix import order using solhint
    - Add new bun scripts: `lint:sol:fix` and `lint:fix`
- Install husky and lint-staged

### Note

To bypass husky hook, just add `-n` to your commit (from [git docs](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---no-verify)).

```shell
> git commit -S -n -m "your message"
```

### CODE REVIEW

**Review by PaulRBerg — APPROVED** [review]
very cool, thanks for this.

I wish this existed when we wrote the first lines of codes in 2022!

**Comment by andreivladbrg** [comment]
Before giving a full review, I want to mention that we should rebase in `staging` from `main` as, for example, the formatting in `precompiles` was already addressed

**Comment by andreivladbrg** [comment]
Coming back re rebase, since there are conflicts between `main` and `staging` and many PRs open to `staging`, I will postpone until we merge all of them into `staging` (expect for this one) and then rebase from `main`.

**Comment by smol-ninja** [comment]
Even if formatting in precompiles was already addressed, why cant we merge it in staging and rebase later (in the end)? Resolving formatting conflicts ain't that hard.

**Comment by andreivladbrg** [comment]
> why cant we merge it in staging and rebase later (in the end)?

we can, but the more commits there are in the staging branch, the more conflicts you’ll need to resolve.

> Resolving formatting conflicts isn't that hard

well, it’s not difficult in terms of complexity, but the more conflicts you have to resolve, the more likely you are to miss something
for example, this issue: https://github.com/sablier-labs/v2-periphery/issues/373 shouldn't have not existed, as the struct was added by mistake when rebased

**Review by andreivladbrg — APPROVED** [review]
The PR looks good, since foundry reverted the formatting style, let's merge this 👍

**Comment by smol-ninja** [comment]
Great. Merging now.

**Pull request merged**
