### PR TITLE
Use absolute paths to import src contracts in test files

### PR DESCRIPTION
**Pull request by smol-ninja**
It improves readability.

### CODE REVIEW

**Comment by andreivladbrg** [comment]
it might improve readability, but the reason why we don't use absolute paths to import src contracts in specific test files is because these might be imported in other repos as well (e.g., [periphery](https://github.com/sablier-labs/v2-periphery/blob/cc0e660e9b8d1277bb8cb0cedd440630d1379c48/test/Base.t.sol#L13-L14)) - and if we make this change, it would revert due to not finding the file

thus, we should not pursue with this change

**Comment by smol-ninja** [comment]
Right. But isn't that only true for `utils` folder since that is part of the npm package?

**Comment by andreivladbrg** [comment]
the repo can be installed as:

```
 "@sablier/v2-core": "github:sablier-labs/v2-core#staging"
```

or as gitmodule:
```
forge install sablier-labs/v2-core
```

we don't know what a person would need from our test files, so we want to offer as much flexibility as possible.

**Comment by smol-ninja** [comment]
I agree. Thanks for your comment.

**Pull request closed without merging**
