### PR TITLE
implementing suggestions from Egis audit review

### PR DESCRIPTION
**Pull request by smol-ninja**
### Changelog
1. Index `admin` in `AllowToHook` event.

> Egis: This way if the admin is changed, it would be easy to query all addresses that were whitelisted by given admin address, etc.

2. Include dash in alphanumeric check

> Egis: Consider adding - (2D) as supported char in for token sybmol, because it is not a threat for JSON injection and there are tokens such as LP, which may use this char. An [example token](https://etherscan.io/token/0xa3ee21c306a700e682abcdfe9baa6a08f3820419) with a market cap of $271M

@andreivladbrg and @PaulRBerg tagging you for feedback on the above changes.

### CODE REVIEW

**Review by PaulRBerg — CHANGES_REQUESTED** [review]
A dash `-` is not an alphanumeric character.

Thus, let's rename the `isAlphanumericWithSpaces` function to `isAllowedCharacter`.

**Comment by smol-ninja** [comment]
Will rename it. I agree with your point but couldn't think of a good name. Will go with `isAllowedCharacter`

**Review by PaulRBerg — APPROVED** [review]
looks good now, great job

**Comment by PaulRBerg** [comment]
Let's wait for @andreivladbrg's review.

**Review by andreivladbrg — APPROVED** [review]
LGTM 👍

**Pull request merged**
