### PR TITLE
feat: disallow sender to be zero address

### PR DESCRIPTION
**Pull request by smol-ninja**
### Changelog
- Closes https://github.com/sablier-labs/v2-core/issues/1008
- Disallow sender to be zero address in all `_create` functions

### CODE REVIEW

**Comment by andreivladbrg** [comment]
Before leaving a full review, is there a specific reason the `params.sender == address(0) `check is not in the `Helpers.checkCreate` function, but in the contracts themselves (LD, LL, LT)?

**Comment by smol-ninja** [comment]
The goal was to revert as soon as possible if `sender` is zero without wasting any gas in `checkAndCalculateBrokerFee` call. Moving it into `Helpers.checkCreate` is technically same but it increases the revert gas cost.

**Comment by andreivladbrg** [comment]
> The goal was to revert as soon as possible

the same argument can be applied to all other checks, but we place them in the library Helpers, as it is better structured, the gas implications are small, so i would suggest to move the check there
wdyt?

**Comment by PaulRBerg** [comment]
Agree with @andreivladbrg, let's move the check in the `Helpers` library. The gas saving should be negligible.

**Comment by smol-ninja** [comment]
> the same argument can be applied to all other checks

I don't think so. The other checks require a call to the `checkAndCalculateBrokerFee` function to update the amount values, which is then followed by the `checkCreateLockupXYZ` function. Whereas `sender` can be checked independently.

**Comment by andreivladbrg** [comment]
> The other checks require a call to the `checkAndCalculateBrokerFee`

the timestamps don't require this

**Comment by smol-ninja** [comment]
I've moved the sender check to `Helpers` library.

**Review by andreivladbrg — APPROVED** [review]
Screenshot 2024-07-22 at 3 18 14 PM

**Comment by PaulRBerg** [comment]
love the LGTM memes

**Pull request merged**
